name: Docker Image CI/CD

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  repo: "oscarcarlsson"
  name: "kanboard-wolfi"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build environment
      uses: ./.github/actions/prepare-build-env
      with:
        kanboard_ref: 'v1.2.47'
      id: buildenv

    - name: Build the Docker image
      run: just build --set repo "$repo" --set name "$name" ${{ steps.buildenv.outputs.date }}

    - uses: anchore/scan-action@v6
      with:
        image: "${{ github.repository }}:${{ steps.buildenv.outputs.date }}"
        fail-build: true
